import type { Hospital } from "@/types";
import { daysAgo } from "./dates";

export const seedHospitals: Hospital[] = [
  {
    id: "hosp-1",
    name: "Grace Specialist Hospital",
    area: "Ikeja",
    city: "Lagos",
    state: "Lagos",
    address: "14 Allen Avenue, Ikeja, Lagos",
    phone: "+234 803 555 0142",
    email: "admin@gracespecialist.ng",
    plan: "premium",
    status: "active",
    bedCount: 120,
    coordinates: { lat: 6.6018, lng: 3.3515 },
    createdAt: daysAgo(420),
  },
  {
    id: "hosp-2",
    name: "Harmony Medical Centre",
    area: "Lekki Phase 1",
    city: "Lagos",
    state: "Lagos",
    address: "7 Admiralty Way, Lekki Phase 1, Lagos",
    phone: "+234 809 555 0177",
    email: "ops@harmonymedical.ng",
    plan: "premium",
    status: "active",
    bedCount: 80,
    coordinates: { lat: 6.4474, lng: 3.4723 },
    createdAt: daysAgo(300),
  },
  {
    id: "hosp-3",
    name: "Riverside Children's Clinic",
    area: "Yaba",
    city: "Lagos",
    state: "Lagos",
    address: "22 Herbert Macaulay Way, Yaba, Lagos",
    phone: "+234 802 555 0110",
    email: "hello@riversidekids.ng",
    plan: "free",
    status: "active",
    bedCount: 40,
    coordinates: { lat: 6.5095, lng: 3.3711 },
    createdAt: daysAgo(150),
  },
  {
    id: "hosp-4",
    name: "Unity Specialist Hospital",
    area: "Wuse II",
    city: "Abuja",
    state: "FCT",
    address: "31 Aminu Kano Crescent, Wuse II, Abuja",
    phone: "+234 806 555 0199",
    email: "info@unityspecialist.ng",
    plan: "premium",
    status: "active",
    bedCount: 150,
    coordinates: { lat: 9.0765, lng: 7.4786 },
    createdAt: daysAgo(260),
  },
  {
    id: "hosp-5",
    name: "Mainland Diagnostics & Surgery",
    area: "Surulere",
    city: "Lagos",
    state: "Lagos",
    address: "5 Adeniran Ogunsanya Street, Surulere, Lagos",
    phone: "+234 701 555 0123",
    email: "care@mainlanddiagnostics.ng",
    plan: "free",
    status: "trial",
    bedCount: 35,
    coordinates: { lat: 6.5, lng: 3.35 },
    createdAt: daysAgo(20),
  },
];
