import type { MachineFilters } from "@/types";

export const queryKeys = {
  machines: (hospitalId: string, filters?: MachineFilters) => ["machines", hospitalId, filters ?? {}] as const,
  machine: (id: string) => ["machine", id] as const,
  machineByCode: (code: string) => ["machine", "code", code] as const,
  machineEvents: (id: string) => ["machine", id, "events"] as const,
  machineDocuments: (id: string) => ["machine", id, "documents"] as const,
  wards: (hospitalId: string) => ["wards", hospitalId] as const,
  hospitalStats: (hospitalId: string) => ["stats", hospitalId] as const,
  faultsPerMonth: (hospitalId: string) => ["stats", hospitalId, "faults"] as const,
  dueForService: (hospitalId: string) => ["stats", hospitalId, "due"] as const,
  jobs: ["jobs"] as const,
  hospitalJobs: (hospitalId: string) => ["jobs", "hospital", hospitalId] as const,
  allJobs: ["jobs", "all"] as const,
  job: (id: string) => ["jobs", "detail", id] as const,
  openJobs: (technicianId: string) => ["jobs", "open", technicianId] as const,
  technicianJobs: (technicianId: string) => ["jobs", "technician", technicianId] as const,
  machineJob: (machineId: string) => ["jobs", "machine", machineId] as const,
  myReports: (userId: string) => ["jobs", "reports", userId] as const,
  technicians: (status?: string) => ["technicians", status ?? "all"] as const,
  technician: (id: string) => ["technicians", "detail", id] as const,
  reviews: (technicianId: string) => ["technicians", "reviews", technicianId] as const,
  nurses: (hospitalId: string) => ["team", hospitalId, "nurses"] as const,
  invites: (hospitalId: string) => ["team", hospitalId, "invites"] as const,
  invite: (code: string) => ["invite", code] as const,
  earnings: (technicianId: string) => ["earnings", technicianId] as const,
  hospitals: ["hospitals"] as const,
  hospital: (id: string) => ["hospitals", id] as const,
  notifications: (userId: string) => ["notifications", userId] as const,
  admin: ["admin"] as const,
};
